---
title: "Zf_scatac_1_CreatSignacObject"
author: "zhangyl"
date: '2023-09-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r}
library(Signac)
library(Seurat)
library(GenomicRanges)
library(future)
library(ggplot2)
library(patchwork)
library(hdf5r)
library(dplyr)
library(readr)
library(pheatmap)
library(ggrepel)
library(LSD)
library(MASS)
library(ensembldb)
```

## Load data

We load features, barcodes, matrix and matadata which were generated by 'Data preproessing' step.

```{r}
mtx_dir_path <- "~/zbf_scATAC_mtx_2/1k"
mtx_path <- paste(mtx_dir_path, "count_matrix_over_aggregate.mtx" , sep = '/')
feature_path <- paste(mtx_dir_path, "count_matrix_over_aggregate.rows" , sep = "/")
barcode_path <- paste(mtx_dir_path, "count_matrix_over_aggregate.cols" , sep = '/')
metadata_path <- paste(mtx_dir_path , "sample_info.csv" , sep = '/')

features <- readr::read_tsv(feature_path, col_names = F) %>% tidyr::unite(feature)
barcodes <- readr::read_tsv(barcode_path, col_names = F) %>% tidyr::unite(barcode)

i = 1
for(i in 1:nrow(barcodes))
{
  s <- strsplit(barcodes$barcode , split = "_")[[i]]
  barcodes[i,1] <- paste(s[c(-1,-2)] , collapse = "_")
}

metadata <- read.csv(file = metadata_path , header = T, row.names = 1)

i = 1
for(i in 1:nrow(metadata))
{
  s <- strsplit(rownames(metadata)[i] , split = "_")[[1]]
  rownames(metadata)[i] <- paste(s[c(-1,-2)] , collapse = "_")
}

mtx <- Matrix::readMM(mtx_path) %>%
  magrittr::set_rownames(features$feature) %>%
  magrittr::set_colnames(barcodes$barcode)
```

## Create Seurat Object

```{r}
chrom_assay <- CreateChromatinAssay(
  counts = mtx,
  sep = c("_" , "_"),
  genome = 'danRer11',
  fragments = paste(mtx_dir_path , 'aggregate_fragments.tsv.gz' , sep = '/'),
)

atac_1k <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  project = 'zbfish_scATAC_1k',
  meta.data = metadata
)

granges(atac_1k)

# Add plate
plate <- data.frame("p1")
i = 1
for(i in 1:ncol(atac_1k))
{
  s <- strsplit(colnames(atac_1k) , split = "_")[[i]]
  plate[i] <- paste(s[2] , "_" ,
                    s[3] ,sep = "")
}
atac_1k$plate <- factor(plate , levels = c("1k_p5","1k_p6","1k_p7","1k_p8","1k_p13","1k_p14"))

# Add batch
atac_1k$batch <- as.character(atac_1k$plate)
atac_1k$batch[atac_1k$batch %in% c('1k_p5' , '1k_p6' , '1k_p7' , '1k_p8')] = "1k_batch1"
atac_1k$batch[atac_1k$batch %in% c('1k_p13' , '1k_p14')] = "1k_batch2"

# Add stage
atac_1k$stage <- "atac_1k"
```

## Annotation

```{r}
ensdb.zbf <- ensDbFromGtf(gtf = "~/danRer11_annotation/Danio_rerio.GRCz11.106.gtf.gz")
ensdb.zbf <- EnsDb(ensdb.zbf)
annotation.zbf <- GetGRangesFromEnsDb(ensdb.zbf)
seqlevelsStyle(annotation.zbf) <- 'UCSC'
genome(annotation.zbf) <- "danRer11"
Annotation(atac_1k) <- annotation.zbf
```

## Quality control

```{r}
# Compute nucleosome signal per cell
atac_1k <- NucleosomeSignal(object = atac_1k)
# Compute TSS enrichment score per cell
atac_1k <- TSSEnrichment(object = atac_1k, fast = FALSE)

VlnPlot(atac_1k , features = c("nFeature_peaks" , "nCount_peaks" , 
                                 "mt_content" , "mapping_rate" , 
                                 "sequencing_depth" , "uniq_nuc_frags" , 
                                 "nucleosome_signal" , "TSS.enrichment") , ncol = 2)
VlnPlot(atac_1k , features = c("nFeature_peaks" , "nCount_peaks" , 
                                 "mt_content" , "mapping_rate" , 
                                 "sequencing_depth" , "uniq_nuc_frags" ,
                                 "nucleosome_signal" , "TSS.enrichment") ,ncol = 2, group.by = "batch")
control.list <- grep("_384" , rownames(atac_1k@meta.data) , value = T)

## Density heatmap
# LSD
heatscatter(log10(atac_1k$uniq_nuc_frags) , atac_1k$TSS.enrichment)

# ggplot
x = log10(atac_1k$uniq_nuc_frags)
y = atac_1k$TSS.enrichment
dens <- kde2d(x , y)
gr <- data.frame(with(dens , expand.grid(x , y)) , as.vector(dens$z))
names(gr) <- c("xgr" , "ygr" , "zgr")
mod <- loess(data = gr , zgr~xgr*ygr)
pointdens <- predict(mod , newdata = data.frame(xgr = x , ygr = y))
bar <- names(pointdens)
d <- as.data.frame(cbind(x , y , pointdens))
d$bar <- bar
colnames(d) <- c("log10_unique_fragments" , "TSS_Enrichment" , "Density" , "Barcode")

ggplot(data = d , aes(x = log10_unique_fragments , y = TSS_Enrichment , color = Density))+
  geom_point()+
  geom_hline(yintercept = 1 , linetype = "dashed")+
  geom_vline(xintercept = 3 , linetype = "dashed")+
  theme_bw()+
  theme(legend.background = element_blank() , panel.grid.major = element_blank() , panel.grid.minor = element_blank())+
  geom_label_repel(data = d[control.list,] , aes(label = Barcode),fontface = "bold" , color = "black",size = 3 , segment.color = "black",
                   point.padding = 1 , box.padding = 1)+
  scale_colour_gradientn(colours = c("grey" , "grey" , rainbow(7)[5:1]))

# Set threshold of nucleosome_signal.
atac_1k$nucleosome_group <- ifelse(atac_1k$nucleosome_signal > 3 , 'NS > 3' , "NS < 3")
FragmentHistogram(atac_1k , group.by = "nucleosome_group")

# Remove outliers
atac_1k_original <- atac_1k
atac_1k <- subset(atac_1k , 
                    subset = uniq_nuc_frags > 1000 & 
                      TSS.enrichment > 1 & 
                      nucleosome_signal < 3 &
                      mapping_rate > 70)
```

## Normalization and visualization

```{r}
atac_1k <- RunTFIDF(atac_1k)
atac_1k <- FindTopFeatures(atac_1k, min.cutoff = 'q0')
atac_1k <- RunSVD(atac_1k)

atac_1k <- RunUMAP(object = atac_1k, reduction = 'lsi', dims = 2:50)
atac_1k <- FindNeighbors(object = atac_1k, reduction = 'lsi', dims = 2:50)
atac_1k <- FindClusters(object = atac_1k, verbose = FALSE, algorithm = 3)
DimPlot(object = atac_1k, label = TRUE) + NoLegend()
DimPlot(object = atac_1k, label = TRUE , group.by = "batch")
DimPlot(object = atac_1k, label = TRUE , group.by = "plate")
FeaturePlot(atac_1k , features = c("nFeature_peaks" , "nCount_peaks" , 
                                     "mt_content" , "mapping_rate" , 
                                     "sequencing_depth" , "uniq_nuc_frags" ,
                                     "nucleosome_signal" , "TSS.enrichment") , ncol = 2)
```

## Save object

```{r}
saveRDS(object = atac_1k_original , file = "~/zbf_scATAC_n/atac_1k_original.RDS")
saveRDS(object = atac_1k , file = "~/zbf_scATAC_n/atac_1k_qc.RDS")
```
